apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod
commonLabels:
  app: canary-prod
bases:
- ../../base
resources:
- canary-rollout.yaml
- canary-service.yaml
- canary-ingress.yaml
- canary-preview-service.yaml
- canary-preview-ingress.yaml
