nameSuffix: -prod
commonLabels:
  app: canary-prod
bases:
- ../../base
patchesStrategicMerge:
- canary-rollout.yaml
- canary-service.yaml
- canary-preview-service.yaml
resources:
- canary-ingress.yaml
- canary-preview-ingress.yaml
