apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
  strategy: {}